//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ordenes
    {
        public int Id { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public System.DateTime FechaUpdate { get; set; }
        public int IdCliente { get; set; }
        public string Identificador { get; set; }
        public string Direccion { get; set; }
        public string Estatus { get; set; }
    }
}
