//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Productos
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public double Precio { get; set; }
        public int CategoriaID { get; set; }
        public bool Estatus { get; set; }
        public int Cantidad { get; set; }
        public Nullable<int> CantidaddeVentas { get; set; }
        public bool Promocionado { get; set; }
        public decimal Calificacion { get; set; }
    }
}
